actor Actor A

@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User
participant Client
participant Связующий_сервис
participant Server
participant База_данных


User -> Client : Запрос Поиска трека
Client -> Server: Запрос Поиска в БД
Server -> База_данных : Поиск по паттерну
activate База_данных
База_данных -> База_данных : Поиск в БД
return Возврат результата
Server -> Client : Возврат результата
Client -> Client : Поиск треков\n по названию
Client -> Client : соединение найденных треков в один лист
Client -> Client : перемешивание?
Client -> User : Возврат результата
== Client нажал сохранить в плейлист ==
User -> Client : Добавить трек в плейлист
Client -> Server: Запрос добавления в плейлист
Server -> База_данных : Запрос есть ли такой\n трек в БД (поиск по Url)
note over База_данных : Если такой трек уже есть
База_данных -> Server : Такой трек уже есть
Server -> База_данных : Добавляем трек в \nплейлист пользователя
Server -> База_данных : Добавляем паттерн из\n поиска пользователя к треку
note over База_данных : Если такого трека нет
База_данных -> Server : Такого трека нет
Server -> База_данных : Добавляем трек в БД \n по паттерну поиска пользователя
note over База_данных : _______
Server -> Client : Готово
Client -> User : Вернуть страницу с \n обновленным плейлистом
@enduml