package ru.one.stream.commons;

public enum MessageType {
    SEARCH_MUSIC,
    MUSIC_ADD_TRACK_TO_LIB,
    MUSIC_DELETE_TRACK_FROM_LIB,
    MUSIC_RENAME_TRACK_FROM_PLAYLIST,
    USERS_GET_USER_DETAILS,
    USERS_GET_USERSPACE
}
