server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: PLAINTEXT://localhost:9092,PLAINTEXT://localhost:29092
    reply-topic: client
    request-topic: server
    producer:
      client-id: client
      retries: 3
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
  mvc:
    view:
      prefix: classpath:templates/
      suffix: .html